### ISSUE TITLE
TRL version requirement

### ISSUE THREAD

**Issue by mjschock** [datadreamer-dev/DataDreamer#20]
Is there a need for `trl` to be locked to 0.7.6 [here](https://github.com/datadreamer-dev/DataDreamer/blob/main/src/requirements.txt#L30)? Can it be relaxed to at least allow 0.8.1 which is compatible with `transformers >= 4.39`?

There's an import that fails otherwise. See https://github.com/huggingface/trl/pull/1415.

**Comment by AjayP13** [comment]
Ah, thanks, let me see what I can do to unlock this (will probably get to
it by this weekend).

Temporarily, however, you can manually install DataDreamer first and then
upgrade transformers afterwards as a second install command.

If you need it more urgently, let me know.

**Comment by AjayP13** [comment]
@mjschock Looks like it was an easy update to make (no tests breaking), so it's out now. This is now fixed on the latest on PyPI (`0.26.0`). Let me know if you have another issues.

**Comment by mjschock** [comment]
thanks @AjayP13 - it works! =)

**Comment by AjayP13** [comment]
Awesome, no problem!
