### ISSUE TITLE
DataDreamer is not working under windows

### ISSUE THREAD

**Issue by AlbelTec** [datadreamer-dev/DataDreamer#26]
Hi,
I noticed that when trying to generate synthetic data, it went in error as it require **"termios"** package which is Posix based.
Can you mention this as prerequisite in you installation documentation so newbies like me will not waste their time trying to install DataDreamer package in windows.
Thanks

**Comment by AjayP13** [comment]
This is clearly documented on the install PyPI page under the requirements. If you want to use the package on Windows, [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/about) is an option.

<img width="297" alt="image" src="https://github.com/datadreamer-dev/DataDreamer/assets/5404177/f666a046-94d1-4a0e-b4ec-61f015e4f84c">

**Comment by AlbelTec** [comment]
Got it thanks.
