### ISSUE TITLE
Support for GPT-4o?

### ISSUE THREAD

**Issue by kmheckel** [datadreamer-dev/DataDreamer#33]
It seems that the API for datadreamer has fallen behind to OpenAI's?

**Comment by kmheckel** [comment]
And GPT-4o-mini?

I can start drafting a PR for this, since all GPT-4 models now offered are chat/instruct models and GPT3.5 is no more.

**Comment by AjayP13** [comment]
Solved on `0.37.0`, thanks for reporting. Sorry for the delay.
