### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by Tankiit** [datadreamer-dev/DataDreamer#4]
While trying to do pip3 install datadreamer.dev
I get the following issues
ERROR: Could not find a version that satisfies the requirement datadreamer.dev (from versions: none)
ERROR: No matching distribution found for datadreamer.dev

Am I doing something wrong ?

**Comment by AjayP13** [comment]
Resolved via Discord, I believe. You need to have a Python version greater than or equal to 3.10 currently.
